Will be learning about Logistic Regression, LDA, KNN

Types of PRediction Problems:
1. The dependent variable to be predicted is continuous : Regression problem
- (Note : Logistic regression is used in classification problems Not in regression problem)
2. Target/Dependent variable is categorical : Classification problem

In [1]:
import numpy as np 
import pandas as pd
import seaborn as sns

In [2]:
data_path = r'D:\MyStudy\ML_DL_Udemy\Machine Learning & Deep Learning in Python & R\Data Files\2. ST Academy - Classification models resource files/Classification preprocessed data Python.csv'

In [3]:
df = pd.read_csv(data_path, header=0)

In [4]:
df.head()

price  resid_area  air_qual  room_num   age  teachers  poor_prop  \
0   24.0       32.31     0.538     6.575  65.2      24.7       4.98   
1   21.6       37.07     0.469     6.421  78.9      22.2       9.14   
2   34.7       37.07     0.469     7.185  61.1      22.2       4.03   
3   33.4       32.18     0.458     6.998  45.8      21.3       2.94   
4   36.2       32.18     0.458     7.147  54.2      21.3       5.33   

   n_hos_beds  n_hot_rooms  rainfall     parks  Sold  avg_dist  airport_YES  \
0       5.480     11.19200        23  0.049347     0    4.0875            1   
1       7.332     12.17280        42  0.046146     1    4.9675            0   
2       7.394     46.19856        38  0.045764     0    4.9675            0   
3       9.268     11.26720        45  0.047151     0    6.0650            1   
4       8.824     11.28960        55  0.039474     0    6.0625            0   

   waterbody_Lake  waterbody_Lake and River  waterbody_River  
0               0                         0                1  
1               1                         0                0  
2               0                         0                0  
3               1                         0                0  
4               1                         0                0

We have 
- 'sold'  - tells wether that property was sold within 3  months of getting listed . 1-> was sold
- 'price' is independent variable in this dataset - showing asking price of the property by owner

Questions from this dataset:
1. Prediction question : Will the house be sold within 3 months of getting listed
2. Inferential question : How accurately can we estimate the effect of each of the predictor variables on the response variable

Q: Why Can't we use Linear regression for more than Two Categories?
- 

With the sigmoid function : we solve the problem of probability lying between 0 and 1 and Outliers (as the slope will not change much and the far away outliers will be lying on the curve)

- In linear regression we used - OLS (Ordinary Least Squares)
- In Logistic Regression we will use - Maximum Likelihood Method

Lets create Logistic Regression Model

In [5]:
X = df[['price']]    # In sklearn - Independent var should be 2d

In [6]:
y = df['Sold']

In [7]:
X.head()

price
0   24.0
1   21.6
2   34.7
3   33.4
4   36.2

In [8]:
y.head()

0    0
1    1
2    0
3    0
4    0
Name: Sold, dtype: int64

In [9]:
from sklearn.linear_model import LogisticRegression

In [10]:
#create classification object
clf_lrs = LogisticRegression()

In [11]:
# train model
clf_lrs.fit(X, y)

LogisticRegression()

In [12]:
# to see value of beta0 and beta1 
clf_lrs.coef_       #beta1

array([[-0.03571865]])

In [13]:
clf_lrs.intercept_    #beta0

array([0.61477516])

Using statsmodel to create logistic regression

In [14]:
import statsmodels.api as sn

In [15]:
# add constant as statsmodel dont have constants default

X_const = sn.add_constant(X)

In [16]:
X_const.head()

const  price
0    1.0   24.0
1    1.0   21.6
2    1.0   34.7
3    1.0   33.4
4    1.0   36.2

In [17]:
import statsmodels.discrete.discrete_model as sm

In [18]:
logit = sm.Logit(y, X_const).fit()

Optimization terminated successfully.
         Current function value: 0.676690
         Iterations 5


In [19]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      504
Method:                           MLE   Df Model:                            1
Date:                Mon, 27 Nov 2023   Pseudo R-squ.:                 0.01788
Time:                        20:36:30   Log-Likelihood:                -342.41
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 0.0004142
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.6149      0.248      2.484      0.013       0.130       1.100
price         -0.0357      0.010     -3.417      0.001      -0.056      -0.015
==============================================================================
"""

If we have more than 2 classes - LDA is preferably used than Logistic regression

In [20]:
#Logistic Regression with Multiple Independent variables

X = df.loc[:, df.columns != 'Sold']    #All columns except sold

y = df['Sold']

In [21]:
clf_lr = LogisticRegression()
clf_lr.fit(X, y)

c:\Users\kajal\miniconda3\envs\ml\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [22]:
clf_lr.coef_

array([[-0.24635667, -0.01729747, -0.11019417,  0.86260547, -0.00599863,
         0.22819691, -0.21021774,  0.18006708, -0.0908669 , -0.00704722,
        -0.00499204, -0.32611296, -0.10521266, -0.09487364, -0.01512366,
         0.20180376]])

In [23]:
clf_lr.intercept_

array([0.0167128])

In [24]:
# For stats model
X_cons = sn.add_constant(X)

In [25]:
logit = sm.Logit(y, X_cons).fit()

Optimization terminated successfully.
         Current function value: 0.556433
         Iterations 6


In [26]:
logit.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results                           
==============================================================================
Dep. Variable:                   Sold   No. Observations:                  506
Model:                          Logit   Df Residuals:                      489
Method:                           MLE   Df Model:                           16
Date:                Mon, 27 Nov 2023   Pseudo R-squ.:                  0.1924
Time:                        20:36:31   Log-Likelihood:                -281.56
converged:                       True   LL-Null:                       -348.64
Covariance Type:            nonrobust   LLR p-value:                 9.930e-21
============================================================================================
                               coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                       -2.1383      2.649     -0.807      0.420      -7.331       3.054
price                       -0.2741      0.033     -8.313      0.000      -0.339      -0.209
resid_area                   0.0192      0.027      0.720      0.471      -0.033       0.071
air_qual                    -7.4183      2.691     -2.757      0.006     -12.693      -2.144
room_num                     1.1067      0.277      4.001      0.000       0.565       1.649
age                         -0.0020      0.007     -0.302      0.762      -0.015       0.011
teachers                     0.3150      0.064      4.937      0.000       0.190       0.440
poor_prop                   -0.2077      0.034     -6.149      0.000      -0.274      -0.141
n_hos_beds                   0.1760      0.071      2.467      0.014       0.036       0.316
n_hot_rooms                 -0.0742      0.052     -1.439      0.150      -0.175       0.027
rainfall                    -0.0033      0.008     -0.394      0.693      -0.020       0.013
parks                       29.1089     24.177      1.204      0.229     -18.277      76.495
avg_dist                    -0.4017      0.098     -4.118      0.000      -0.593      -0.211
airport_YES                 -0.1524      0.211     -0.723      0.469      -0.565       0.261
waterbody_Lake              -0.1032      0.304     -0.340      0.734      -0.698       0.492
waterbody_Lake and River    -0.0626      0.328     -0.191      0.849      -0.705       0.580
waterbody_River              0.2394      0.256      0.937      0.349      -0.262       0.740
============================================================================================
"""

Confusion Matrix:
1. Type I Error / False Positive : Predicted True but Actually it was False
2. Type II Error / False Negative: Predicted False but Actually it was True

In [27]:
clf_lr.predict_proba(X)

array([[0.12706708, 0.87293292],
       [0.39755021, 0.60244979],
       [0.98071884, 0.01928116],
       ...,
       [0.2859436 , 0.7140564 ],
       [0.28061211, 0.71938789],
       [0.16347233, 0.83652767]])

In [28]:
y_pred = clf_lr.predict(X)      #by default this .predict() takes threshold 0.5
y_pred

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,

In [29]:
# To set custom boundary conditions/threshold
y_pred_03 = (clf_lr.predict_proba(X)[:, 1] >= 0.3)    #comparing 2nd column values with 0.3

In [30]:
y_pred_03

array([ True,  True, False,  True, False, False,  True, False, False,
        True,  True,  True, False,  True,  True,  True,  True, False,
        True,  True, False,  True, False, False,  True,  True,  True,
        True,  True,  True, False,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True, False, False, False,  True,  True,  True,  True,
       False, False, False, False,  True,  True,  True, False,  True,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False, False,
        True,  True,  True,  True,  True,  True, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False, False, False,  True,
       False, False,

In [31]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y, y_pred)

array([[196,  80],
       [ 81, 149]], dtype=int64)

In [32]:
confusion_matrix(y, y_pred_03)


array([[121, 155],
       [ 18, 212]], dtype=int64)

Performance Measures:
1. False Positive Rate : Type 1 Error : 1-Specificity : FP/N
2. True Positive Rate  : 1 - Type II Error : Power : Sensitivity : Recall : TP / P
3. Positive Predicted value : Precision : TP/Predicted P 
4. Negative Predicted value : TN / Predicted Negative


1. Accuracy= (TP+TN+FP+FN) / (TP+TN)
2. Precision (Positive Predictive Value) = (TP+FP) / TP
​3. Recall (Sensitivity, True Positive Rate) = (TP+FN) / TP
4. F1 Score (Harmonic Mean of Precision and Recall) = 2 ×[ (Precision × Recall) /  (Precision + Recall) ]

​

​


​
 


In [33]:
from sklearn.metrics import precision_score, recall_score

In [34]:
precision_score(y, y_pred)

0.6506550218340611

In [35]:
recall_score(y, y_pred)

0.6478260869565218

In [36]:
from sklearn.metrics import roc_auc_score

In [37]:
roc_auc_score(y, y_pred)

0.6789855072463769

LDA : Linear Discriminant Analysis
It is a dimensionality reduction and classification technique. LDA is particularly useful for finding the linear combinations of features that best separate multiple classes in a dataset. It is often used for classification tasks and is closely related to the more general technique of Principal Component Analysis (PCA).
- Derived from Bayes thearem

In [38]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [39]:
clf_lda = LinearDiscriminantAnalysis()
clf_lda.fit(X, y)

LinearDiscriminantAnalysis()

In [40]:
y_pred_lda = clf_lda.predict(X)

In [41]:
y_pred_lda

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,

In [42]:
confusion_matrix(y, y_pred_lda)

array([[192,  84],
       [ 79, 151]], dtype=int64)

Train Test Split

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.2, random_state=0)

In [45]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape )

(404, 16) (102, 16) (404,) (102,)


In [46]:
clf_LR = LogisticRegression()
clf_LR.fit(X_train, y_train)

c:\Users\kajal\miniconda3\envs\ml\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [47]:
y_test_pred = clf_LR.predict(X_test)

In [48]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [49]:
confusion_matrix(y_test, y_test_pred)

array([[37, 21],
       [14, 30]], dtype=int64)

In [50]:
accuracy_score(y_test, y_test_pred)

0.6568627450980392

KNN Classifier:


In [51]:
# Before running KNN, standardize the independent variables
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(X_train)
X_train_s = scaler.transform(X_train)

In [52]:
scaler = preprocessing.StandardScaler().fit(X_test)
X_test_s = scaler.transform(X_test)

In [53]:
X_test_s

array([[ 3.46427198e-02, -1.26009787e+00, -7.59976330e-01, ...,
        -4.93864798e-01, -3.98862018e-01, -7.54473836e-01],
       [ 3.08888478e+00,  1.09537107e+00,  6.84309089e-01, ...,
        -4.93864798e-01, -3.98862018e-01, -7.54473836e-01],
       [ 7.92301952e-02,  4.28041039e-01,  1.73890573e-04, ...,
        -4.93864798e-01, -3.98862018e-01, -7.54473836e-01],
       ...,
       [-4.00085165e-01, -9.60512654e-01, -8.19099125e-01, ...,
        -4.93864798e-01, -3.98862018e-01,  1.32542701e+00],
       [ 6.47720506e-01, -9.50442563e-02, -5.15039037e-01, ...,
        -4.93864798e-01, -3.98862018e-01, -7.54473836e-01],
       [-2.77469608e-01, -4.16820968e-01, -2.53209516e-01, ...,
        -4.93864798e-01,  2.50713268e+00, -7.54473836e-01]])

when we standardize any variable we convert all of the mean of those variables to 0 and std deviation to 1

In [54]:
from sklearn.neighbors import KNeighborsClassifier
clf_knn_1 = KNeighborsClassifier(n_neighbors=1)
clf_knn_1.fit(X_train_s, y_train)

KNeighborsClassifier(n_neighbors=1)

In [55]:
confusion_matrix(y_test, clf_knn_1.predict(X_test_s))

array([[30, 28],
       [19, 25]], dtype=int64)

In [56]:
accuracy_score(y_test, clf_knn_1.predict(X_test_s))

0.5392156862745098

In [57]:
clf_knn_3 = KNeighborsClassifier(n_neighbors=3)
clf_knn_3.fit(X_train_s, y_train)
accuracy_score(y_test, clf_knn_3.predict(X_test_s))


0.5392156862745098

Creating single model for multiple values of k

In [58]:
from sklearn.model_selection import GridSearchCV

In [59]:
params = {'n_neighbors': [1,2,3,4,5,6,7,8,9,10]}

In [60]:
grid_search_cv = GridSearchCV(KNeighborsClassifier(), params)

In [61]:
grid_search_cv.fit(X_train_s, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [62]:
# check different attributes to find out best parameter from params

grid_search_cv.best_params_

{'n_neighbors': 9}

In [63]:
optimised_KNN = grid_search_cv.best_estimator_

In [64]:
y_test_pred = optimised_KNN.predict(X_test_s)

In [65]:
confusion_matrix(y_test, y_test_pred)

array([[36, 22],
       [18, 26]], dtype=int64)

In [66]:
accuracy_score(y_test, y_test_pred)

0.6078431372549019